# Generated by Django 6.1 on 2026-08-24 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('branches', '0001_initial'),
        ('retailers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='retailers.retailer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PLATFORM_OWNER', 'Super User'), ('RETAILER_ADMIN', 'Super Admin'), ('BRANCH_ADMIN', 'Admin'), ('PHARMACIST', 'Pharmacist'), ('CASHIER', 'Cashier'), ('STAFF', 'Staff')], default='STAFF', max_length=30),
        ),
    ]
